### PR TITLE
Set and keep user params for API credentials and queries

### PR DESCRIPTION
**Pull request by domvwt**
In this PR we:

- allow the user to set their Authorization bearer token in the newsapi request headers
- fix a bug where the requested `num_stories` is not preserved in all branches of `signals.sample_stories_in_window`
- allow arbitrary keyword arguments to be added to the request in `signals.make_query`

### CODE REVIEW

**Review by chrishokamp — CHANGES_REQUESTED** [review]
@domvwt thank you very much for adding the Authorization header kwarg

I believe arbitrary params for queries is already supported via the `params` field of `AylienSignal`, could you double check that please? 
https://github.com/AYLIEN/news-signals-datasets/blob/main/news_signals/signals.py#L736
https://github.com/AYLIEN/news-signals-datasets/blob/main/news_signals/signals.py#L583

If what you want to do is not supported please add at least one unittest proving the new functionality (please add at least one unittest regardless)

**Comment by chrishokamp** [comment]
@domvwt unittest(s) should go here please https://github.com/AYLIEN/news-signals-datasets/blob/main/news_signals/test_signals.py

**Comment by complementizer** [comment]
@domvwt Thanks! If your change wrt `num_stories` fixes the issue for you go ahead. I think I'll make an update next week to generalise `per_page` and `n_pages` to `num_stories` or `stories_per_day` in all places of the library.

**Comment by domvwt** [comment]
@chrishokamp, @complementizer - I've added a unit test to confirm that the `num_stories` parameter is passed through to the request. All test pass except for the following:
```
======================================================================
ERROR: test_add_wikipedia_current_events (news_signals.test_signals.TestAylienSignal)
----------------------------------------------------------------------
...
news_signals.newsapi.TimeseriesEndpointError: [{'code': 'KB401', 'detail': 'application key "<REMOVED>" is invalid', 'id': 'error401_unauthorized', 'links': {'about': 'https://docs.aylien.com/newsapi/#authorization'}, 'status': 401, 'title': 'Unauthorized'}]
```

Do we want to update this to use the new request headers?

**Comment by domvwt** [comment]
> @domvwt thank you very much for adding the Authorization header kwarg
> 
> I believe arbitrary params for queries is already supported via the `params` field of `AylienSignal`, could you double check that please? [`main`/news_signals/signals.py#L736](https://github.com/AYLIEN/news-signals-datasets/blob/main/news_signals/signals.py?rgh-link-date=2024-01-26T10%3A47%3A59Z#L736) [`main`/news_signals/signals.py#L583](https://github.com/AYLIEN/news-signals-datasets/blob/main/news_signals/signals.py?rgh-link-date=2024-01-26T10%3A47%3A59Z#L583)
> 
> If what you want to do is not supported please add at least one unittest proving the new functionality (please add at least one unittest regardless)

Adding arbitrary params works fine - the only time there's a problem is when `num_stories` is provided to `sample_stories_in_window` we need to update the request in all code branches.

**Comment by chrishokamp** [comment]
@domvwt thank you this is super useful 👏

**Pull request merged**
